// <auto-generated />
using System;
using GarageManagement.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GarageManagement.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260223103731_AddedBaseEntity")]
    partial class AddedBaseEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookAppointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AppointmentTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceAdvisor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId1")
                        .HasColumnType("bigint");

                    b.Property<long?>("VehicleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("WorkshopId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.HasIndex("VehicleId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("BookAppointment", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.AdditionalJobObserveDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RepairOrderId")
                        .HasColumnType("bigint");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupervisorInstructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicianVoice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RepairOrderId");

                    b.ToTable("AdditionalJobObserveDetail", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.CheckItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Control")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TechnicianMCId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TechnicianMCId");

                    b.ToTable("CheckItem", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.InventoryAccessory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Checked")
                        .HasColumnType("bit");

                    b.Property<long>("InventoryFormId")
                        .HasColumnType("bigint");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("InventoryFormId");

                    b.ToTable("InventoryAccessory", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.InventoryForm", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RepairOrderId")
                        .HasColumnType("bigint");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("RepairOrderId")
                        .IsUnique()
                        .HasFilter("[RepairOrderId] IS NOT NULL");

                    b.ToTable("InventoryForm", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.JobCard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AlternateMobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("AvgKmsPerDay")
                        .HasColumnType("bigint");

                    b.Property<string>("Corporate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsuranceCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobCardNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("OdometerIn")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Paid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RepairOrderId")
                        .HasColumnType("bigint");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<string>("ServiceAdvisor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceSuggestions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Technician")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RepairOrderId");

                    b.ToTable("JobCard", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.JobCardAdvancePayment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Cash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ChequeNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("JobCardId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("JobCardId")
                        .IsUnique();

                    b.ToTable("JobCardAdvancePayment", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.JobCardCancelledInvoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("JobCardId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("JobCardId");

                    b.ToTable("JobCardCancelledInvoice", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.JobCardCollection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChequeNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("JobCardId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobCardId");

                    b.ToTable("JobCardCollection", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.JobCardConcern", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long>("JobCardId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobCardId");

                    b.ToTable("JobCardConcern", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.JobCardEstimationItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HSN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssuedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("IssuedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssuedId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IssuedQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("JobCardId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("PartId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RequestedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobCardId");

                    b.HasIndex("PartId");

                    b.ToTable("JobCardEstimationItem", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.JobCardTyreBattery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("JobCardId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ManufactureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobCardId");

                    b.ToTable("JobCardTyreBattery", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.LabourDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LabourCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OutsideLabour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("RepairOrderId")
                        .HasColumnType("bigint");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("RepairOrderId");

                    b.ToTable("LabourDetail", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.Part", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RackNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("TaxPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TaxType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PartNo")
                        .IsUnique();

                    b.ToTable("Part", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.PermissionModule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("PermissionModule", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.RepairOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AllottedTechnician")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("BookingAppointmentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DriverPermanetToThisVehicle")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ExpectedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mkls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RepairEstimationCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("RoadTestAlongWithDriver")
                        .HasColumnType("bit");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<string>("SiteInchargeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfService")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UnderWarranty")
                        .HasColumnType("bit");

                    b.Property<string>("VehicleSite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VinNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingAppointmentId");

                    b.ToTable("RepairOrder", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.RolePermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("PermissionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PermissionModuleId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("PermissionModuleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermission", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.SparePartsIssueDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<long?>("RepairOrderId")
                        .HasColumnType("bigint");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RepairOrderId");

                    b.ToTable("SparePartsIssueDetail", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.StockMovement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EstimationItemId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("PartId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EstimationItemId");

                    b.HasIndex("PartId");

                    b.HasIndex("UserId");

                    b.ToTable("StockMovement", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.TechnicianMC", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AuthSign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverSign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FloorSign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RepairOrderId")
                        .HasColumnType("bigint");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<string>("TechnicianSign")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RepairOrderId")
                        .IsUnique()
                        .HasFilter("[RepairOrderId] IS NOT NULL");

                    b.ToTable("TechnicianMC", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.ToBeFilledBySupervisor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverVoice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RepairOrderId")
                        .HasColumnType("bigint");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupervisorInstructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RepairOrderId");

                    b.ToTable("ToBeFilledBySupervisor", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResetTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.Vehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegPrefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Vehicle", (string)null);
                });

            modelBuilder.Entity("GarageManagement.Server.Model.WorkshopUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId1")
                        .HasColumnType("bigint");

                    b.Property<long>("WorkshopId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.HasIndex("WorkshopId");

                    b.ToTable("WorkshopUser", (string)null);
                });

            modelBuilder.Entity("PaymentMode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("PaymentMode", (string)null);
                });

            modelBuilder.Entity("Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Service", (string)null);
                });

            modelBuilder.Entity("WorkshopAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BranchAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlatNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Landmark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WorkshopId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopId")
                        .IsUnique();

                    b.ToTable("WorkshopAddress", (string)null);
                });

            modelBuilder.Entity("WorkshopBusinessConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DefaultServiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalIntegrationUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GSTIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleReviewLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceCaption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceHeader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MSME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<string>("SAC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SACPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WebsiteLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WorkshopId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopId")
                        .IsUnique();

                    b.ToTable("WorkshopBusinessConfig", (string)null);
                });

            modelBuilder.Entity("WorkshopMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<long>("WorkshopId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopId");

                    b.ToTable("WorkshopMedia", (string)null);
                });

            modelBuilder.Entity("WorkshopPaymentMode", b =>
                {
                    b.Property<long>("WorkshopId")
                        .HasColumnType("bigint");

                    b.Property<long>("PaymentModeId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.HasKey("WorkshopId", "PaymentModeId");

                    b.HasIndex("PaymentModeId");

                    b.ToTable("WorkshopPaymentMode", (string)null);
                });

            modelBuilder.Entity("WorkshopProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AvgVehicleInflowPerMonth")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CalendarDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DealerCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InBusinessSince")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsGdprAccepted")
                        .HasColumnType("bit");

                    b.Property<string>("Landline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("NoOfEmployees")
                        .HasColumnType("int");

                    b.Property<string>("OwnerMobileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<string>("WorkshopName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkshopProfile", (string)null);
                });

            modelBuilder.Entity("WorkshopService", b =>
                {
                    b.Property<long>("WorkshopId")
                        .HasColumnType("bigint");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.HasKey("WorkshopId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("WorkshopService", (string)null);
                });

            modelBuilder.Entity("WorkshopTiming", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<long>("WorkshopId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopId")
                        .IsUnique();

                    b.ToTable("WorkshopTiming", (string)null);
                });

            modelBuilder.Entity("WorkshopWorkingDay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<long>("WorkshopId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopId");

                    b.ToTable("WorkshopWorkingDay", (string)null);
                });

            modelBuilder.Entity("BookAppointment", b =>
                {
                    b.HasOne("GarageManagement.Server.Model.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GarageManagement.Server.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("GarageManagement.Server.Model.User", null)
                        .WithMany("BookAppointments")
                        .HasForeignKey("UserId1");

                    b.HasOne("GarageManagement.Server.Model.Vehicle", "Vehicle")
                        .WithMany("Appointments")
                        .HasForeignKey("VehicleId");

                    b.HasOne("WorkshopProfile", "Workshop")
                        .WithMany("Appointments")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Customer");

                    b.Navigation("User");

                    b.Navigation("Vehicle");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.AdditionalJobObserveDetail", b =>
                {
                    b.HasOne("GarageManagement.Server.Model.RepairOrder", "RepairOrder")
                        .WithMany("AdditionalJobObserveDetails")
                        .HasForeignKey("RepairOrderId");

                    b.Navigation("RepairOrder");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.CheckItemEntity", b =>
                {
                    b.HasOne("GarageManagement.Server.Model.TechnicianMC", "TechnicianMC")
                        .WithMany("CheckList")
                        .HasForeignKey("TechnicianMCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TechnicianMC");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.InventoryAccessory", b =>
                {
                    b.HasOne("GarageManagement.Server.Model.InventoryForm", "InventoryForm")
                        .WithMany("Accessories")
                        .HasForeignKey("InventoryFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryForm");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.InventoryForm", b =>
                {
                    b.HasOne("GarageManagement.Server.Model.RepairOrder", "RepairOrder")
                        .WithOne("InventoryForm")
                        .HasForeignKey("GarageManagement.Server.Model.InventoryForm", "RepairOrderId");

                    b.Navigation("RepairOrder");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.JobCard", b =>
                {
                    b.HasOne("GarageManagement.Server.Model.RepairOrder", "RepairOrder")
                        .WithMany()
                        .HasForeignKey("RepairOrderId");

                    b.Navigation("RepairOrder");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.JobCardAdvancePayment", b =>
                {
                    b.HasOne("GarageManagement.Server.Model.JobCard", "JobCard")
                        .WithOne("AdvancePayment")
                        .HasForeignKey("GarageManagement.Server.Model.JobCardAdvancePayment", "JobCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobCard");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.JobCardCancelledInvoice", b =>
                {
                    b.HasOne("GarageManagement.Server.Model.JobCard", "JobCard")
                        .WithMany("CancelledInvoices")
                        .HasForeignKey("JobCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobCard");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.JobCardCollection", b =>
                {
                    b.HasOne("GarageManagement.Server.Model.JobCard", "JobCard")
                        .WithMany("Collections")
                        .HasForeignKey("JobCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobCard");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.JobCardConcern", b =>
                {
                    b.HasOne("GarageManagement.Server.Model.JobCard", "JobCard")
                        .WithMany("Concerns")
                        .HasForeignKey("JobCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobCard");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.JobCardEstimationItem", b =>
                {
                    b.HasOne("GarageManagement.Server.Model.JobCard", "JobCard")
                        .WithMany("JobCardEstimationItems")
                        .HasForeignKey("JobCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GarageManagement.Server.Model.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId");

                    b.Navigation("JobCard");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.JobCardTyreBattery", b =>
                {
                    b.HasOne("GarageManagement.Server.Model.JobCard", "JobCard")
                        .WithMany("TyreBatteries")
                        .HasForeignKey("JobCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobCard");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.LabourDetail", b =>
                {
                    b.HasOne("GarageManagement.Server.Model.RepairOrder", "RepairOrder")
                        .WithMany("LabourDetails")
                        .HasForeignKey("RepairOrderId");

                    b.Navigation("RepairOrder");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.RepairOrder", b =>
                {
                    b.HasOne("BookAppointment", "BookAppointment")
                        .WithMany()
                        .HasForeignKey("BookingAppointmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BookAppointment");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.RolePermission", b =>
                {
                    b.HasOne("GarageManagement.Server.Model.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GarageManagement.Server.Model.PermissionModule", "PermissionModule")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionModuleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GarageManagement.Server.Model.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("PermissionModule");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.SparePartsIssueDetail", b =>
                {
                    b.HasOne("GarageManagement.Server.Model.RepairOrder", "RepairOrder")
                        .WithMany("SparePartsIssueDetails")
                        .HasForeignKey("RepairOrderId");

                    b.Navigation("RepairOrder");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.StockMovement", b =>
                {
                    b.HasOne("GarageManagement.Server.Model.JobCardEstimationItem", "EstimationItem")
                        .WithMany("StockMovements")
                        .HasForeignKey("EstimationItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GarageManagement.Server.Model.Part", "Part")
                        .WithMany("StockMovements")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GarageManagement.Server.Model.User", "User")
                        .WithMany("StockMovements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EstimationItem");

                    b.Navigation("Part");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.TechnicianMC", b =>
                {
                    b.HasOne("GarageManagement.Server.Model.RepairOrder", "RepairOrder")
                        .WithOne("TechnicianMC")
                        .HasForeignKey("GarageManagement.Server.Model.TechnicianMC", "RepairOrderId");

                    b.Navigation("RepairOrder");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.ToBeFilledBySupervisor", b =>
                {
                    b.HasOne("GarageManagement.Server.Model.RepairOrder", "RepairOrder")
                        .WithMany("ToBeFilledBySupervisors")
                        .HasForeignKey("RepairOrderId");

                    b.Navigation("RepairOrder");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.User", b =>
                {
                    b.HasOne("GarageManagement.Server.Model.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.Vehicle", b =>
                {
                    b.HasOne("GarageManagement.Server.Model.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.WorkshopUser", b =>
                {
                    b.HasOne("GarageManagement.Server.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GarageManagement.Server.Model.User", null)
                        .WithMany("WorkshopUsers")
                        .HasForeignKey("UserId1");

                    b.HasOne("WorkshopProfile", "Workshop")
                        .WithMany("WorkshopUsers")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("WorkshopAddress", b =>
                {
                    b.HasOne("WorkshopProfile", "Workshop")
                        .WithOne("Address")
                        .HasForeignKey("WorkshopAddress", "WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("WorkshopBusinessConfig", b =>
                {
                    b.HasOne("WorkshopProfile", "Workshop")
                        .WithOne("WorkshopBusinessConfigs")
                        .HasForeignKey("WorkshopBusinessConfig", "WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("WorkshopMedia", b =>
                {
                    b.HasOne("WorkshopProfile", "Workshop")
                        .WithMany("WorkshopMedias")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("WorkshopPaymentMode", b =>
                {
                    b.HasOne("PaymentMode", "PaymentMode")
                        .WithMany()
                        .HasForeignKey("PaymentModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkshopProfile", "Workshop")
                        .WithMany("WorkshopPaymentModes")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentMode");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("WorkshopService", b =>
                {
                    b.HasOne("Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkshopProfile", "Workshop")
                        .WithMany("Services")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("WorkshopTiming", b =>
                {
                    b.HasOne("WorkshopProfile", "Workshop")
                        .WithOne("Timing")
                        .HasForeignKey("WorkshopTiming", "WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("WorkshopWorkingDay", b =>
                {
                    b.HasOne("WorkshopProfile", "Workshop")
                        .WithMany("WorkingDays")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.Customer", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.InventoryForm", b =>
                {
                    b.Navigation("Accessories");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.JobCard", b =>
                {
                    b.Navigation("AdvancePayment");

                    b.Navigation("CancelledInvoices");

                    b.Navigation("Collections");

                    b.Navigation("Concerns");

                    b.Navigation("JobCardEstimationItems");

                    b.Navigation("TyreBatteries");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.JobCardEstimationItem", b =>
                {
                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.Part", b =>
                {
                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.PermissionModule", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.RepairOrder", b =>
                {
                    b.Navigation("AdditionalJobObserveDetails");

                    b.Navigation("InventoryForm");

                    b.Navigation("LabourDetails");

                    b.Navigation("SparePartsIssueDetails");

                    b.Navigation("TechnicianMC");

                    b.Navigation("ToBeFilledBySupervisors");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.TechnicianMC", b =>
                {
                    b.Navigation("CheckList");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.User", b =>
                {
                    b.Navigation("BookAppointments");

                    b.Navigation("StockMovements");

                    b.Navigation("WorkshopUsers");
                });

            modelBuilder.Entity("GarageManagement.Server.Model.Vehicle", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("WorkshopProfile", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Appointments");

                    b.Navigation("Services");

                    b.Navigation("Timing");

                    b.Navigation("WorkingDays");

                    b.Navigation("WorkshopBusinessConfigs");

                    b.Navigation("WorkshopMedias");

                    b.Navigation("WorkshopPaymentModes");

                    b.Navigation("WorkshopUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
