@GarageManagement.Server_HostAddress = http://localhost:5238

POST {{GarageManagement.Server_HostAddress}}/WorkshopProfile/save

POST {{GarageManagement.Server_HostAddress}}/bookingAppointment/saveBookAppointment

POST {{GarageManagement.Server_HostAddress}}/Auth



Accept: application/json

###
